### ISSUE TITLE
Brother! Thanks for the app , but

### ISSUE THREAD

**Issue by Akczht** [bingzheung/authenticator#1]
Hey man can you please! add a better icon for the app , current one looks ugly Af , this app is the most feature rich free app for 2fa and I thank you for that , the beat 2FA app for my use case .

Thanks!

**Comment by bingzheung** [comment]
Hi @akczht 

Thank you for the advise

**Comment by Akczht** [comment]
> Hi @akczht 
> 
> 
> 
> Thank you for the advise

Hey! @ososoio If you can add an option to import qr images from the files app , and also add icons for Tutanota.com , mailo.com , CTemplar.com and Eclipso.eu . Then this'll be the best 2FA app out there . Also as far as personalisation is concerned , here is a vey basic logo suggestion ![image](https://user-images.githubusercontent.com/79302042/118116294-bcc91e80-b407-11eb-878c-55494a97a845.png) and also here are some suggestions for the name of the app , if you like 'em then please! implement any one , like OTP-Auth , Authenticator , OTP-Gen , 2FA .

Thanks!

**Comment by Akczht** [comment]
It's ok brother [OTP Auth](https://apps.apple.com/in/app/otp-auth/id659877384) is just better .
