### ISSUE TITLE
Secret keys stored in CoreData?

### ISSUE THREAD

**Issue by ricardopereira** [bingzheung/authenticator#3]
I think there's a security flaw. Shouldn't the secret keys be stored in the Keychain instead of a CoreData model which can be extracted from the app and access them with small effort?
Thanks for your great work!

**Comment by bingzheung** [comment]
Hi @ricardopereira 

Yes, it is a weakness. I do plan to reimplement it with Keychain, but I don't have that time yet.

This project was started as an experimental project at first, it isn't well designed.

With iOS Sandbox, I think the current data security is acceptable if we're not extremely concern about it.
