### ISSUE TITLE
AppStore Review

### ISSUE THREAD

**Issue by Plus1XP** [bingzheung/authenticator#4]
Apologies for making an issue, I wanted to contact you to ask about your app approval. 
I recently decided to move my fork from TestFlight to AppStore but it got rejected because they wanted to know how the token is verified (screenshot below). 
Did you encounter this issue? If so how did you resolve it?

Thanks

![image](https://user-images.githubusercontent.com/24768549/165334079-11dd3e52-d423-40e6-9258-c35ec5a53de9.png)

**Comment by bingzheung** [comment]
Hi @Plus1XP 

I've never seen this before, perhaps providing a Key URI sample would help.
Like `otpauth://totp/Company:email@example.com?secret=JBSWY3DPEHPK3PXP&issuer=Company`
