### ISSUE TITLE
Support for steam tokens

### ISSUE THREAD

**Issue by inprealpha** [bingzheung/authenticator#5]
First of all, really nice app, well worth the price I paid! Thanks!

So the only issue I've faced till now is that the app does not work with exported Steam Tokens. Apparently Steam uses 5 digit keys or something. I haven't tried it but I am pretty sure it'll work the same way directly from QR codes as well. 

So other 2FA apps have a special steam mode or some other mechanism.

I'll link some issues regarding this faced by other apps-

https://github.com/helloworld1/FreeOTPPlus/pull/113
https://github.com/andOTP/andOTP/issues/475
https://gitlab.gnome.org/World/Authenticator/-/issues/115

It'll be really helpful if you could add Steam support, bonus points if I don't have to re-enter the token!

**Comment by bingzheung** [comment]
Hi @inprealpha 

Thank you for the information, I will try to implement this.

**Comment by bingzheung** [comment]
Hi @inprealpha 

This project depends on [SwiftOTP](https://github.com/lachlanbell/SwiftOTP).

And the bad news is SwiftOTP does not support 5 digits.

https://github.com/lachlanbell/SwiftOTP/blob/0ace411e76ae290fecf6c7d15c6d7c3eee9ccd0c/SwiftOTP/TOTP.swift#L45-L48

Looks like I can't implement it in the short term.

**Comment by inprealpha** [comment]
Hi @ososoio 

According to this

https://github.com/lachlanbell/SwiftOTP/issues/22

the digit limit is only a soft limit and can be circumvented.

**Comment by inprealpha** [comment]
That said, perhaps digits are not the only limitation? According to this

https://github.com/andOTP/andOTP/issues/38 - there are also letters.

It links some tiny implementations, perhaps you could look into it?

EDIT: Another example https://github.com/geekdada/steam-otp 


EDIT2: https://web.archive.org/web/20170703060102/https://winauth.com/2015/06/11/steam-guard-mobile/ 
this says that they use standard totp (RFC6238, whichever standard that is), but with 5 digits.

**Comment by bingzheung** [comment]
Hi @inprealpha 

Thanks for the information.

Looks like this Steam case is more complicated than I thought.  

There's too much work to do to implement it, I think maybe this app should just focus on the normal TOTP.
